node_type: eagerx_bridge_openai_classic_control.openai_bridge/OpenAIBridge
default:
  rate:
  outputs: [tick]
  process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxbridge.launch'
  color: magenta
  is_reactive: True
  real_time_factor: 0  # 0 == as fast as possible

outputs:
  tick:
    msg_type: std_msgs.msg/UInt64