node_type: eagerx_bridge_openai_classic_control.simnodes/TorqueControl
default:
  rate:
  inputs: [tick, torque]
  outputs: [torque_applied]
  process: 2  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxnode.launch'

inputs:
  tick:
    msg_type: std_msgs.msg/UInt64
    repeat: all
  torque:
    msg_type: std_msgs.msg/Float64
    repeat: last

outputs:
  torque_applied:
    msg_type: std_msgs.msg/Float64