version: 2

conda:
    environment: docs/environment.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# This part is necessary otherwise the project is not built
python:
   version: 3.7
   install:
      - method: pip
        path: .

# By default readthedocs does not checkout git submodules
submodules:
    include: all