node_type: eagerx_core.basebridge/TestBridgeNode
default:
  rate:
  outputs: [tick]
  process: 0  # {0: NEW_PROCESS, 1: ENVIRONMENT, 2: BRIDGE, 3: EXTERNAL}
  launch_file: '$(find eagerx_core)/launch/rxbridge.launch'
  color: magenta
  num_substeps: 10
  nonreactive_address: '/nonreactive_input_topic'

outputs:
  tick:
    msg_type: std_msgs.msg/UInt64
