default:
  sensors: [N6]
  actuators: [ref_vel]
  states: [N8, N9]
  position: [0, 0, 0]
  orientation: [0, 0, 0]

sensors: # Outputs of simulators
  N6:
    rate: 1
    msg_type: UInt64
    msg_module: std_msg.msg

actuators: # Inputs of simulators
  N7:
    rate: 1
    msg_type: UInt64
    msg_module: std_msg.msg
    # Add converter module if used directly as action_space: UInt64_to_space(**converter_args)
    # Add converter arguments:
  ref_vel:
    rate: 1
    msg_type: UInt64
    msg_module: std_msg.msg

states: # Outputs of simulators
  N8:
    rate: 1
    msg_type: UInt64
    msg_module: std_msg.msg
  N9:
    rate: 1
    msg_type: UInt64
    msg_module: std_msg.msg

bridge:
  urdf: 'path/to/urdf.urdf'
  sensors:
    N6:
      node_type: SimSensorNode
      module: eagerx_core.params

  actuators:  # Inputs as defined above
    N7:
      node_type: SimActuatorNode
      module: eagerx_core.params
      inputs: [P5]
      inputs_address: [N5/P5]

  states:
    N8:
      node_type: SimStateNode
      module: eagerx_core.params
    N9:
      node_type: SimStateNode
      module: eagerx_core.params
      inputs: [N6]
      inputs_address: [obj/sensors/N6]