default:
  sensors: [N6]
  actuators: [ref_vel]
  states: [N8, N9]
  position: [0, 0, 0]
  orientation: [0, 0, 0]

#########################
## Agnostic definition ##
#########################
sensors: # inputs of env
  N6:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    gym_space:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: boxu64
      low: [0]
      high: [100]

actuators: # outputs of env
  N7:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    gym_space:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: boxu64
      low: 0
      high: 100
      shape: (1,)  # optional
  ref_vel:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    gym_space:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: boxu64
      low: [0]
      high: [100]

states: # inputs/outputs of env
  N8:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    gym_space:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: boxu64
      low: [0]
      high: [100]
  N9:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    gym_space:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: boxu64
      low: [0]
      high: [100]


#########################
### Engine definition ###
#########################
bridge:
  urdf: 'path/to/urdf.urdf'
  sensors:
    N6:
      node_config: eagerx_core/sim_sensor
      outputs: {out_1: sensors/N6}
      test_arg: 'CHANGED ARGUMENT'

  actuators:  # Inputs as defined above
    N7:
      node_config: eagerx_core/sim_actuator
      inputs: {action_1: actuators/N7}
#      input_converters:
#        converter_type: eagerx_core.converter/SpaceUInt64Converter
#        test_arg: 'test'
      test_arg: 'CHANGED ARGUMENT'

  states:
    N8:
      node_config: eagerx_core/sim_sensor
      outputs: {out_1: states/N8}
      test_arg: 'CHANGED ARGUMENT'
    N9:
      node_config: eagerx_core/sim_sensor
      inputs: {in_1: sensors/N6}
      outputs: {out_1: states/N9}
      test_arg: 'CHANGED ARGUMENT'
