default:
  sensors: [N6, N7]
  actuators: [ref_vel]
  states: [N9, N10]
  position: [0, 0, 0]
  orientation: [0, 0, 0]

#########################
## Agnostic definition ##
#########################
sensors: # inputs of env
  N6:
    rate: 2
    msg_type: std_msgs.msg/UInt64
  N7:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

actuators: # outputs of env
  N8:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: 0
      high: 100
      shape: (1,)  # optional
  ref_vel:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

states: # inputs/outputs of env
  N9:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]
  N10:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

#########################
### Engine definition ###
#########################
bridge:
  urdf: 'path/to/urdf.urdf'
  sensors:
    N6:
      node_config: eagerx_core/sim_sensor # These nodes cannot have an internal state
      test_arg: 'CHANGED ARGUMENT'
    N7:
      node_config: eagerx_core/sim_sensor # These nodes cannot have an internal state
      inputs: {in_1: sensors/N6}
      test_arg: 'CHANGED ARGUMENT'

  actuators:  # Inputs as defined above
    N8:
      node_config: eagerx_core/sim_actuator
      actuator_input: action_1  # input name from outside object (inside node_config "sim_actuator.yaml")
      inputs: {action_2: sensors/N6}
#      input_converters:  # can only contain converters for inputs other than "actuator_input"
#        action_2:
#          converter_type: eagerx_core.converter/SpaceUInt64Converter
#          test_arg: 'test'
      test_arg: 'CHANGED ARGUMENT'

  states:
    N9:
      node_config: eagerx_core/sim_state
      state_input: state_1 # state name from outside object (inside node_config "sim_state.yaml")
      test_arg: 'CHANGED ARGUMENT'
    N10:
      node_config: eagerx_core/sim_state
      state_input: state_1 # state name from outside object (inside node_config "sim_state.yaml")
      test_arg: 'CHANGED ARGUMENT'
